### PR TITLE
Hello world for Javascript

### PR DESCRIPTION
**Pull request by HrushikeshBodas**

### CODE REVIEW

**Comment by agarwalrounak** [comment]
Hi @HrushikeshBodas, thanks a lot for your contribution. 
Do you want this PR to be counted in your hacktoberfest stats? If so, only PRs from 1 Oct - 31 Oct will be counted.

**Comment by HrushikeshBodas** [comment]
yes, i want it to be counted towards hacktoberfest, can you merge this tomorrow?

**Comment by HrushikeshBodas** [comment]
hey @agarwalrounak can you merge this?

**Comment by agarwalrounak** [comment]
Hi @HrushikeshBodas! Thank you so much for your contributions. I am quite excited about it. 

If you enjoyed contributing to this project, please [share](https://bit.ly/hacktoberfest19) and star this project to help as many people as possible to get started in Open Source.

**Pull request merged**
